### ISSUE TITLE
enable syntax highlighting

### ISSUE THREAD

**Issue by markheath** [evilz/vscode-reveal#1]
awesome extension, just wondering if there is a way to enable syntax highlighting?
For example, if I do this, the correct highlightjs tags seem to get generated in HTML but the style sheets seem to be missing so there is no syntax highlighting.

    ```csharp
    var x = Hello.World("Hello World");
    ```

**Comment by evilz** [comment]
Thank,

I'm fixing it right now. 
Stay up to date
