### ISSUE TITLE
Side by side wiev does not refresh

### ISSUE THREAD

**Issue by paddelkraft** [evilz/vscode-reveal#10]
Thanks guys for the tool love it.

I might have missed something but i have not found a way to get the side by side view to refresh when
the MD file is updated. exept triggering a new side by side view

it would be neice to be able to reload it or even auto reload on changes

**Comment by evilz** [comment]
Hi,

The refresh should work on save on md file. It should go directly to the slide where your mouse is in the editor.

Can you explain what are you doing exactly ?

Thank

**Comment by evilz** [comment]
It's look like someting has changed with VS Code.
I need to find what, thank for reporting this !
