### ISSUE TITLE
4.3.2 won't render in browser or preview (Windows 10)

### ISSUE THREAD

**Issue by fuhrmanator** [evilz/vscode-reveal#1005]
Something is very broken in the 4.3.2 release. I had to install 4.3.1 to get it working again. Pages render with a stack dump, starting with

> Error: Cannot find module 'ejs' Require stack:

**Comment by evilz** [comment]
On it release right now the fix

**Comment by evilz** [comment]
@fuhrmanator v4.3.3 release ! 

Give me feed back !.

I need to make documentation. We can do so manythings now.
Custom css
Custom css variables
Custom init !
