### ISSUE TITLE
Command Stop server in status bar throws an error

### ISSUE THREAD

**Issue by michaelfery** [evilz/vscode-reveal#107]
Click on square button of status bar to stop server throws an error 'vscode-reveal.killRevealJSServer' not found
![image](https://user-images.githubusercontent.com/5047542/51588466-8b4d8180-1ee4-11e9-9598-e60bd3fb55cb.png)

**Comment by evilz** [comment]
Yes, it should be fixed in next realese 😁

**Comment by evilz** [comment]
Should be fixed in V3.0.0
