### ISSUE TITLE
Support using style name instead of file name for highlight theme

### ISSUE THREAD

**Issue by unional** [evilz/vscode-reveal#1076]
Highlight themes name with two or more words doesn't work.

For example, `Github Dark` doesn't work, but `github-dark` does.

**Comment by evilz** [comment]
Yes this filename that you can find here: https://github.com/evilz/vscode-reveal/tree/master/libs/highlight.js/11.3.1/styles

**Comment by unional** [comment]
Yes, I want thinking about adding that to the README, so that it is more clear.
However it would be better to support it as the README suggest (using double quotes "..." implies it takes two or more words such as "Github Dark")

**Comment by evilz** [comment]
Since there is the autocompletion it's not really a issue.

**Comment by unional** [comment]
oh~~, never noticed the autocompletion. thx!
