### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by DmitryMaletin** [evilz/vscode-reveal#121]
VSCode version - 1.31.0
Extension version - 3.0.0

Slides doesn't appear after markdown document was opened.  
Render server seems to be not started.
I've tried to uninstall/install extension but it doesn't help.

**Comment by vbshift** [comment]
Do you have a output panel with any detail ?

**Comment by DmitryMaletin** [comment]
Activating extension 'evilz.vscode-reveal' failed: Cannot find module 'lodash'.

**Comment by vbshift** [comment]
thank

**Comment by evilz** [comment]
Can you test the last version.  (3.2.0)

**Comment by babichss** [comment]
> Can you test the last version. (3.2.0)

Same

**Comment by evilz** [comment]
Can you tell me any message and system and version used ?

**Comment by babichss** [comment]
> Can you tell me any message and system and version used ?

VSCode 1.31
vscode-reveal 3.2.0

It works now, but don't recognize `---` as slides splitter, transforming them into `<hr>`

**Comment by evilz** [comment]
do you jump line before and after `---`  ?

The default split is "^[\r\n?|\n]---[\r\n?|\n]$"

**Comment by babichss** [comment]
@evilz yes

**Comment by babichss** [comment]
@evilz also output is not synced when opened in browser tab.
Side display is synced.

**Comment by babichss** [comment]
@evilz custom themes are also broken

**Comment by evilz** [comment]
@babichss yes this has not change only split view is sync ans only in one way.

**Comment by evilz** [comment]
I close this issue since title is **not working at all**
