### ISSUE TITLE
Default separator broken

### ISSUE THREAD

**Issue by rdeneau** [evilz/vscode-reveal#123]
_Versions : vscode-reveal extension = 3.2.0, vscode = 1.31.0 (January 2019)_

When no slide separator is specified, `---` works fine with the extensions (slide count, slide explorer) but does not work in the side preview and in the browser: only one slide is recognized.

When `---` is specified as slide separator in the header, side preview and in browser rendering are fine but slide count and slide explorer now take into account the `---` used to specify the header.

Example:
```md
---
highlightTheme: "darkula"
slideNumber: true
separator: ^( ?| )---( ?| )$
---

# Hello

Slide 1

---

## Slide 2

Slide 2

---

Slide 3
```

When defining and using `----` as slide separator, slide count and slide explorer are still falsy.

**Comment by evilz** [comment]
Thank,

not sure why, but this should work

```
separator: ^---$
```

**Comment by evilz** [comment]
this regex `^( ?| )---( ?| )$` create 3 groups each time don't use group in regex :)

**Comment by robert-skarzycki** [comment]
I have same issue with _vscode-reveal=3.31_ and _vscode=1.31.0 (January 2019)_ :(

**Comment by evilz** [comment]
Can you give me your file ?

**Comment by robert-skarzycki** [comment]
@evilz, here you can find content of repro file: https://gist.github.com/robert-skarzycki/bfd05150581d819e1ae0bd59e6dc68a6
Current version: _vscode-reveal=3.3.2_ and _vscode=1.31.1_

**Comment by rndmh3ro** [comment]
FYI: the same problem exists with the notesSeparator.
I have to manually add `notesSeparator: 'notes?:'` so the separator works..

**Comment by Henry78** [comment]
https://github.com/evilz/vscode-reveal/issues/127#issuecomment-463264482

**Comment by Henry78** [comment]
Just to note: This happens to my after a fresh installation (no settings changes, just installed vscode-reveal and few other extensions) and by creating a new .md-file with just a separator ("---")

**Comment by evilz** [comment]
Just change regex in version 3.4.0

Can someone check please

**Comment by ericop** [comment]
@evilz I'd be willing to install `vsCode-reaveal-3.4.0.vsix` if you build one. I tried to pull down the repo and run it in debugger, but got this error while trying to open a markdown file to test the new `---` separator.

![image](https://user-images.githubusercontent.com/5218249/55750756-01588380-5a12-11e9-8308-6e88fd53ea6e.png)

**Comment by evilz** [comment]
It's on the marketing. But if should compile. I will check

**Comment by ericop** [comment]
Ah, the badge says `3.3.2` so it confused me.

![image](https://user-images.githubusercontent.com/5218249/55757730-b7c46480-5a22-11e9-911b-a78de831478c.png)

So I removed the frontmatter

```
separator: '^\r?\n---\r?\n$'
verticalSeparator: '^\r?\n--\r?\n$'
```

and it's still working! So I'm pretty sure the default of `^?---?$` is working great as well as `^?--?$` for the *vertical separator*.

Probably just an update to the readme docs, and you should be good!

![image](https://user-images.githubusercontent.com/5218249/55757817-02de7780-5a23-11e9-8457-be45cf8d0438.png)

Thanks again for this cool extension!

**Comment by evilz** [comment]
Ok I need to update documentation.

Maybe I'm going to remove some configuration from Extension menu and only do it from front matter.

**Comment by ericop** [comment]
I like that you added so many things like the separators o the
configuration. I think most of use VS Code users like to have the ability
to tweak defaults under the hood and have those settings persist.

Are there a few which are causing maintenance to this project to be a pain
@evilz ?

**Comment by evilz** [comment]
The pain is only the packages.json file .... so big and verbose.
