### ISSUE TITLE
Rendering/export broken with version > 3.0

### ISSUE THREAD

**Issue by stonebanks** [evilz/vscode-reveal#127]
Hi,
I'm coming across some errors making the extension not usable since the version 3.0.0 (2.03 being the last working version )

this is a screen shot of what I have in the side panel or in the browser
![image](https://user-images.githubusercontent.com/1909018/52501113-958ea180-2bad-11e9-9386-b52a5d181445.png)

and the following errors inside the chrome console: 
![image](https://user-images.githubusercontent.com/1909018/52500673-95da6d00-2bac-11e9-92e9-2750f0f12004.png)

My setup: 
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by evilz** [comment]
Thank reporting this.
I'm on it.

**Comment by evilz** [comment]
Can you try the version 3.3.1 ?
Look's like I got problem with font awesome but I don't know why :(

**Comment by stonebanks** [comment]
No, I just checked and I still have the exact same errors with 3.3.1 :(

**Comment by evilz** [comment]
Are you trying to put this on slideshare ?

**Comment by asalber** [comment]
I have the same problem. 
The presentation renders perfectly from VScode even if you open it in a browser, but it doesn't work when you export it as static html.

**Comment by evilz** [comment]
@asalber My bad I forgot to mention a big breaking change. You need a web server cause now reveal js is using directly the markdown file. I mean it's an ajax request.

Use can use this chrome extension https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en or any web server.

**Comment by asalber** [comment]
I usually host my presentations on github and they worked perfectly until now, even using this chrome extension. 
You can try this: https://github.com/asalber/manual-git
Thanks!

**Comment by evilz** [comment]
Thanks for the link I take a look 😅

**Comment by distantcam** [comment]
I just had the same problem. Switching the markdown file from `CRLF` to `LF` fixed the problem for me.

**Comment by evilz** [comment]
@stonebanks, it should not be a problem by default. But since I'm now on Mac maybe I miss something.

@asalber I just publish a new version that increase timeout before stoping export can you try.
Thank

**Comment by visglz** [comment]
@distantcam Thanks for the hint. I had the same problem. After the update I had to change the lineendings in the markdown files from CR/LF to LF ( I am working under Windows). @evilz Is this a behaviour of reveal.js? I wonder, because before the update it rendered correctly with CR/LF.

**Comment by stonebanks** [comment]
@distantcam Thanks your workaround did the trick!

**Comment by distantcam** [comment]
Another solution is to add these custom separator values to the yaml frontmatter.

```
separator: '^\r?\n---\r?\n$'
verticalSeparator: '^\r?\n--\r?\n$'
```

Pretty sure the fix is to change the default values in `Configuration.ts`.

**Comment by asalber** [comment]
@evilz I've tried to install the new version but I can not generate the vsix file to install it locally. I get the error:

```
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
sh: 1: tsc: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vscode-reveal@3.3.0 vscode:prepublish: `tsc -p ./`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vscode-reveal@3.3.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
I work with Linux (Kubuntu) and I have installed node version 10.15.1 and npm version 6.4.1.

The solution proposed by @distantcam does not work in my case.

**Comment by distantcam** [comment]
@asalber Try installing Typescript and try again

    npm i -g typescript

**Comment by asalber** [comment]
Thanks @distantcam! Now I got the vsix for version 3.3.2, but the problem still continues :disappointed:

**Comment by vbshift** [comment]
@distantcam Does your regex fix the problem ?

I need to and test for this :p

**Comment by ghirardinicola** [comment]
It was very useful to have a static html in order to distribute a dynamic version of the presentation.
Do you know if there is an alternative way to have that kind of feature without asking people to install a browser plugin?

**Comment by evilz** [comment]
Oki, thanks to tell me your needs 😊. 
I will revert this behaviour to a real static HTML.

**Comment by ghirardinicola** [comment]
Thank you, really appreciate!

**Comment by drrui** [comment]
@distantcam  it really works! 
but there is some problems with the font size....all the words are too small...
how to solve it ？

**Comment by distantcam** [comment]
@drrui I don't know? I'm not the maintainer of this project. Please open another issue and provide more details like a screenshot, what system you're running, steps to reproduce. Thanks

**Comment by drrui** [comment]
@distantcam  Sorry, thanks a lot for your help.

**Comment by ghirardinicola** [comment]
@evilz can you point me at where to look to change the export to static html please?

**Comment by evilz** [comment]
Hi, not sure to understand what you are looking for or what you want to do

**Comment by fuhrmanator** [comment]
In 3.4.0 I'm getting the same result as the OP (identical screenshot). If I start with a simple project, all the slides are combined on one page (the `---` cause horizontal lines, everything is on one slide, etc.).
