### ISSUE TITLE
Pause with B or . does not toggle the pause black screen in normal mode

### ISSUE THREAD

**Issue by jon301** [evilz/vscode-reveal#131]
Some information about what I've noticed about this :

In normal mode, it looks like pressing `B` or `.` does not toggle the pause black screen (pressing those does not do anything actually).

However in speaker view mode, I noticed that `B` toggles the chalkboard, and `.` toggles the pause black screen correctly

Is there any way to toggle the pause black screen in normal mode ?

**Comment by jon301** [comment]
Sorry, I've just seen that it behaves like that in the reveal js example website
e.g. https://revealjs.com/#/23

Still, there is a conflict between `B` pause shortcut and `b` chalkboard shortcut in speaker mode :)
No big deal

**Comment by evilz** [comment]
Thank, 

Ok I see the chalkboard is show in Speaker View. 
Not my code in fact, and not a big since you need to write on slide show anyway.

**Comment by jon301** [comment]
I love this extension btw, thanks @evilz !
