### ISSUE TITLE
Problem with background in Highlight Theme

### ISSUE THREAD

**Issue by anrichter** [evilz/vscode-reveal#141]
Hi,

i use a light (white) theme and want to put some code in a dark highlight theme like monokai.
Unfortunateley the background of hjs elements are always set to none.

    ---
    title: Bug with highlightTheme
    theme: "simple"
    highlightTheme: "monokai"
    ---

    ```bash
    cd ~/src
    mkdir newProject
    cd newProject
    ```

Actual is:
![wrong](https://user-images.githubusercontent.com/72196/53122227-620d2900-3556-11e9-9809-b7d658faf608.png)

Should be:
![ok](https://user-images.githubusercontent.com/72196/53122244-6c2f2780-3556-11e9-9a80-5dc86fd5f730.png)

**Comment by anrichter** [comment]
Found the problem in file views/template.marko.
There is the following style setting:

    .hljs {
      background: none;
    }

When i remove this lines, the highlightTheme works ok.
I want to provide a pull request. But im not sure, what about the other style-settings in the template. The original reveal html does not have all of this.

Greetings
Andreas

**Comment by evilz** [comment]
Thanks, I will fix this.
Attention least you can use `!important` flagrant un css.

Sorry for this

**Comment by anrichter** [comment]
How can i use !important in the front matter?

**Comment by evilz** [comment]
#142  Same

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.

**Comment by anrichter** [comment]
It looks good. Bug is fixed.

Thx & Greetings
