### ISSUE TITLE
Disabling plugins

### ISSUE THREAD

**Issue by maxrothman** [evilz/vscode-reveal#149]
Is there a way to disable plugins? I don't like the chalkboard and title-footer ones, for example.

**Comment by evilz** [comment]
Actually it's not possible, I will add this.

Behaviour will be all enable by default then you will have to disable one by one in conf (header also)

**Comment by evilz** [comment]
Just added in version 3.4.0
Thank

**Comment by evilz** [comment]
Need more settings

**Comment by evilz** [comment]
DONE
