### ISSUE TITLE
Export compiles empty js files

### ISSUE THREAD

**Issue by maxrothman** [evilz/vscode-reveal#150]
OS: Mac 10.14.3
VSCode: 1.31.1
vscode-reveal: 3.3.2

Steps to reproduce:

* Run the "Revealjs: Export in HTML" command in VSCode
* cd to the export directory

Expected results: running a HTTP server, I can view the presentation

Actual results: all the JS files are empty, so you get an error in the console saying `Reveal` is not defined.

Proof:
```
-/export $ find . -type f -not -size 0b -not -name .DS_Store
./markdown.md
./index.html
```

**Comment by edwardbrowncross** [comment]
I am also seeing this. Tested on Windows and Linux:

OS: Windows 10
VScode: 1.31.1
vscode-reveal: 3.3.2

OS: Ubuntu 18.10
VScode: 1.31.1
vscode-reveal: 3.3.2

**Comment by evilz** [comment]
Hum,  thank for reporting this.

I will try to look at this bug.

**Comment by evilz** [comment]
Can you check using version 3.4.0
Thank

**Comment by benignoc** [comment]
Yes, same problem. Checked with 3.4.0 and still getting a blank index.html.

Also, when doing "revealjs open presentation in browser" the presentation is shown but without breaks between sections. only an horizontal bar.

Thanks,
Benigno.

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.
