### ISSUE TITLE
show by side or export in html  did not work correctly

### ISSUE THREAD

**Issue by drrui** [evilz/vscode-reveal#152]
![_20190228235511](https://user-images.githubusercontent.com/24643117/53579415-7c797f00-3bb4-11e9-8424-a83f82508939.png)

also,i can not open it in the browser...what's the problem.

![_20190301002417](https://user-images.githubusercontent.com/24643117/53581466-961cc580-3bb8-11e9-9cd1-79c5a4401d0b.png)

**Comment by drrui** [comment]
vscode reveal: 3.3.2
vs code: 1.31.1 
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by drrui** [comment]
by adding these custom separator values to the yaml frontmatter，i can preview the slides by side.

```
separator: '^\r?\n---\r?\n$'
verticalSeparator: '^\r?\n--\r?\n$'
```


but there is some problems with the font size....all the words are too small...
how to solve it ？
![_20190301123601](https://user-images.githubusercontent.com/24643117/53616651-9b146000-3c1e-11e9-80cf-e474d9b105fb.png)
vs code version: 1.31.1 (user setup)
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134


And another problem is that the presentation can not render on the web server (nginx) after export in HTML.

**Comment by evilz** [comment]
Maybe writing `black`and not `balck` ;P

**Comment by drrui** [comment]
@evilz  ahhhhh！ sorry.  it is my fault.

And the 2nd problem, i did not find the solution. Steps are:
1.  in vs code, export in HTML
2. upload the index.html 、markdown.md and libs folder to my server and right web directory
3. start the nginx server
but the web page is blank with nothing.

**Comment by drrui** [comment]
also, after export in HTML and render it in chrome with plugin(Web Server for Chrome
0.4.8), it is blank too.

**Comment by drrui** [comment]
I did know the reason...
when I modified the directory of the md file, the presentation can render successfully.
In the exported index.html, the directory of md file is "\markdown.md", and I just delete the "\" .

**Comment by evilz** [comment]
Can you check using version 3.4.0
Thank
