### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghuba** [evilz/vscode-reveal#168]
Two possible bugs I have noticed:

1. Math. From the example in the github repo:

```
\[
\begin{aligned}
\dot{x} &amp; = \sigma(y-x) \\
\dot{y} &amp; = \rho x - y - xz \\
\dot{z} &amp; = -\beta z + xy
\end{aligned}
\]
```

The equation is not rendered correctly.

![image](https://user-images.githubusercontent.com/4511360/54854158-5032b900-4caf-11e9-8c53-ff97a5599983.png)

The script syntax does work:
```
<script type="math/tex; mode=display">
  \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
</script>
```

![image](https://user-images.githubusercontent.com/4511360/54854198-6b9dc400-4caf-11e9-8e8e-eb8e982fd78f.png)

2. When exporting to HTML, there is an error in the javascript.

Click on "Export to HTML"

![image](https://user-images.githubusercontent.com/4511360/54854258-99830880-4caf-11e9-8d41-90e56ddb9741.png)

Open index.html

![image](https://user-images.githubusercontent.com/4511360/54854284-aacc1500-4caf-11e9-86e1-1148257f95cd.png)

Console error in Chrome:

![image](https://user-images.githubusercontent.com/4511360/54854311-be777b80-4caf-11e9-8b13-70745c5f1212.png)

Offending line

![image](https://user-images.githubusercontent.com/4511360/54854458-3776d300-4cb0-11e9-8a6c-c4934e7f5be5.png)

The browser page is empty except for the `reveal` logo in the top left.

VS Code Version 1.32.3
vscode-reveal 3.3.2
macOS Mojave 10.14.3
Chrome 72.0.3626.121

**Comment by ghuba** [comment]
More info on this. For bug # 2

```
find . -type f -not -size 0k -not -name .DS_Store
./markdown.md
./index.html
```
So in fact all the files are empty.

This is a duplicate of https://github.com/evilz/vscode-reveal/issues/150#issue-414374765

**Comment by evilz** [comment]
Close (duplicated)

**Comment by ghuba** [comment]
Has bug 1 been reported before? I think only bug 2 is a duplicate.
