### ISSUE TITLE
Add all plugins. Config enable/disable

### ISSUE THREAD

**Issue by kambing86** [evilz/vscode-reveal#18]
there is no way to add plugins now

try to add chalkboard.js plugin

```
---
theme : "night"
transition: "slide"
history: true
dependencies: [
  { src: "./chalkboard.js" }
]
---
```

and this will overwrite the whole dependencies

**Comment by evilz** [comment]
True,

Plugins are currently hard installed.
I think I can add all o them.

**Comment by evilz** [comment]
Plugins to support :

- [] anything
- [] audio-slideshow: 
- [] broadcast
- [] chalkboard
- [] chart
- [] customcontrols
- [] mathsvg
- [] spreadsheet
- [] D3.js plugin
- [] reveal.js-diagram-plugin
- [] https://github.com/gcalmettes/reveal.js-d3
- [] https://github.com/marcysutton/reveal-a11y
- [] https://github.com/rajgoel/reveal.js/tree/animate/plugin/animate (Demo)
- [] https://github.com/chrismetcalf/reveal.js-fullscreen-img
- [] https://github.com/ysmood/notell
- [] https://github.com/crossbario/crossbar-examples/tree/master/iotcookbook/device/browser/revealremote
- [] https://github.com/functino/reveal.js-wave-plugin (Demo)
- [] https://github.com/bibixx/reveal.js-gamepad-plugin
- [] https://github.com/sebhildebrandt/reveal.js-tagcloud-plugin
- [] https://gist.github.com/jbrown123/9445384733c9f289d6e8
- [] https://github.com/Sonaryr/reveal.js-otf-fragment-order
- [] https://github.com/j13z/reveal.js-math-katex-plugin
- [] https://github.com/demoneaux/reveal-code-focus (Demo)
- [] https://github.com/SethosII/reveal.js-jump-plugin
- [] https://github.com/gneatgeek/reveal.js-leap-motion
- [] https://github.com/soluml/reveal-css-snippet
- [] https://github.com/e-gor/Reveal.js-TOC-Progress (Demo)
- [] https://github.com/e-gor/Reveal.js-Title-Footer (Demo)
- [] https://github.com/calevans/external
- [] https://github.com/janschoepke/reveal_external
- [] https://github.com/ctangel/RevealEditor
- [] https://github.com/stevegrunwell/reveal-ga
- [] https://github.com/roccomuso/reveal.js-mqtt-plugin
- [] https://github.com/ldionne/reveal-sampler
- [] https://gist.github.com/geek1011/1841acca111b7dbb3cd902497f255ba0
- [] https://github.com/pragdave/reveal-embed-video
- [] https://github.com/ignatandrei/ppt2reveal/tree/master
- [] https://github.com/Gottox/reveal.js-ace (Demo)
- [] https://github.com/mschmo/reveal-speech (Demo)
- [] https://github.com/dluxemburg/reveal-run-in-terminal
- [] https://github.com/Sonaryr/reveal.js-coursemod
- [] https://github.com/JeremyHeleine/KaTeX-for-reveal.js
- [] https://github.com/tkrkt/reveal.js-elapsed-time-bar (Demo)
- [] https://www.topbug.net/revealjs-explicit-link/ (Source)
- [] https://github.com/jamjolu/tts_basics_for_revealjs
- [] https://github.com/ThomasWeinert/reveal-badges

**Comment by adrienpacifico** [comment]
Hi, total beginner here.
Is there a workaround that we can use in order to use plugins with vscode-reveal ?
Best

**Comment by evilz** [comment]
Hello,

Actually no 😥. 
Tell me what plug-in you want to use. I can try a fast release today maybe.

**Comment by ThinkBriK** [comment]
Hi !

Is there any of those plugins in the current release ?

**Comment by adrienpacifico** [comment]
Hi,
Since no box is ticked, I think none of those plugins are implemented.
@evilz, thank you very much, no urgent matter here, I think I'll try to go full reveal.js and I'll use your plugin for fast-made presentation. Many thank for that plugin !

**Comment by pragdave** [comment]
Could we perhaps have an intermediate solution where we include plugins in a local `node_modules` directory, and then have a `customPlugins` option that lists the ones to load from there, in addition to the ones that are bundled with vscode-reveal?

**Comment by evilz** [comment]
@pragdave Very nice idea ! 
Can try to do this

**Comment by dezGusty** [comment]
Hey there, is there any update on the plug-ins topic? I would also appreciate to be able to add the chalkboard plug-in to my presentations (maybe some charting too). I see that it's not an easy solution however, as Template.js seems to require editing in several places to add plug-in support.

(btw) Great work with the extension!

**Comment by evilz** [comment]
I work on new version with many new things :)   should be in few weeks \O/

**Comment by evilz** [comment]
Hi @jhgoodwin. 
I'm working on it, but I'm not sur to be ready for this date .... sorry

You can take a look at the branch version3. Open it in VS code and push F5.
Tell me what is ok or not.

Thank

**Comment by jhgoodwin** [comment]
@evilz thanks, I will try it tonight 👍

**Comment by evilz** [comment]
V3 is released !
