### ISSUE TITLE
Add function for Insert Seperator and Insert Vertical Seperator

### ISSUE THREAD

**Issue by androids00** [evilz/vscode-reveal#19]
I think it seem good to add function for Insert Separator and Insert Vertical Separator. with setting character in User setting

**Comment by evilz** [comment]
Not sure to understand ??

Are you talking about this https://github.com/evilz/vscode-reveal/blob/master/package.json#L53-L62

**Comment by androids00** [comment]
I mean function for context menu and command pallet.
To insert Separator to document with setting character

**Comment by evilz** [comment]
I don't think I'm going to do this since it easier to just write `---` or `--` that call a command.

But I'm going to show slides in a panel on left and so you should be able to add/remove slide by clicking on a button.

**Comment by androids00** [comment]
I think that's better.
Thanks
