### ISSUE TITLE
respect index.html from reveal.js

### ISSUE THREAD

**Issue by rokroskar** [evilz/vscode-reveal#191]
I use a standalone web server with my reveal.js presentations and for this I have an `index.html` where I specify some options, theming etc. Is it possible for vscode-reveal to respect this `index.html`? For example, to use a custom theme, I modify this in the header of my `index.html`, however for the as per the docs for this extension I should add it to my markdown file - this breaks my "normal" reveal.js slides. Is there some way around it?

**Comment by evilz** [comment]
Any sample please ?

**Comment by fuhrmanator** [comment]
@rokroskar I worked around this by not using the YAML and just setting the options in the index.html from the reveal.js install to set those options, then loading the `.md` file. 

The `index.html` file generated by vscode-reveal is only compatible with the revealjs install done by the plug-in (which is fragile, e.g., see #207 which applies to Windows 10). I see the good side as it (sort of) works immediately after you install the plug-in (nothing else needs installing). However, I could live with the plug-in requiring (or installing) a standard node install of revealjs. This would make the complexity of the install be up to the user, although I'm not sure how easy it is for a tool to do `npm start` to launch the web server in a directory that's outside of `.vscode` space.

**Comment by evilz** [comment]
Do not understand.
