### ISSUE TITLE
Add message when express server cannot start

### ISSUE THREAD

**Issue by ragerin** [evilz/vscode-reveal#20]
I receive the following error when issuing both of the vscode-reveal commands.

`Running the contributed command:'vscode-revealjs.showRevealJS' failed.`

Any ideas?

**Comment by evilz** [comment]
Hi,

Not at all ^^.  
Can you give VS code and extension Version please. And may be your markdown.

Thank for the report.

**Comment by ragerin** [comment]
Of course:

### Versions
| Platform | Version |
| ---------|:----|
| Windows | `8 x64` |
| VSCode | `1.18.1` |
|vscode-reveal | `1.0.0` |

### Data
[sample.md](https://raw.githubusercontent.com/evilz/vscode-reveal/master/sample.md)

### Logs
[-1512387956713.log](https://github.com/evilz/vscode-reveal/files/1526873/-1512387956713.log)

**Comment by evilz** [comment]
Thank for the log file.

It seems that vscode-reveal cannot start a express server.
Did you accept to open the port ? 
You should see a Windows modal asking it.

Maybe that's it. 
Anyway I should add an explicit message if I can.
Thank
