### ISSUE TITLE
3.4.0 has no mathjax fonts (Windows 10)

### ISSUE THREAD

**Issue by fuhrmanator** [evilz/vscode-reveal#207]
I'm trying to use ``$$math$$`` and it's not working in Chrome preview.

Debugging in chrome inspect shows that the math fonts are not found on the localhost server. Looking in `C:\Users\USER\.vscode\extensions\evilz.vscode-reveal-3.4.0\libs\reveal.js\3.7.0\plugin\math\` I see there is indeed no fonts folder.

I confirm that with `npm install -g mathjax` I can copy the fonts folder from the global space into the above and the fonts problems goes away. I think 3.4.0 is just not installing it?

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.

**Comment by fuhrmanator** [comment]
I tried it on a machine that has no reveal installed at all (only 4.0.1 in VSCode).

Opening `sample.md` from this repo shows 32 slides, but when I click on that link, the preview in VSCode shows one big slide with all 32 smooshed together.

"Open presentation in browser" has a similar view, but here's what's in the console of Chrome:

```
localhost/:16 GET http://localhost:53055/libs/reveal.js/font-awesome-4.7.0/css/font-awesome.min.css net::ERR_ABORTED 404 (Not Found)
localhost/:17 GET http://localhost:53055/libs/reveal.js/3.8.0/css/reveal.css net::ERR_ABORTED 404 (Not Found)
localhost/:19 GET http://localhost:53055/libs/reveal.js/3.8.0/css/theme/night.css net::ERR_ABORTED 404 (Not Found)
localhost/:22 GET http://localhost:53055/libs/reveal.js/3.8.0/plugin/title-footer/title-footer-mod.css net::ERR_ABORTED 404 (Not Found)
localhost/:25 GET http://localhost:53055/libs/reveal.js/3.8.0/plugin/mermaid/mermaid.min.js net::ERR_ABORTED 404 (Not Found)
localhost/:99 GET http://localhost:53055/libs/highlight.js/9.12.0/monokai.css net::ERR_ABORTED 404 (Not Found)
localhost/:267 GET http://localhost:53055/logo.png 404 (Not Found)
(index):110 GET http://localhost:53055/libs/reveal.js/3.8.0/css/print/paper.css net::ERR_ABORTED 404 (Not Found)
(anonymous) @ (index):110
(index):1202 GET http://localhost:53055/libs/reveal.js/3.8.0/lib/js/head.min.js net::ERR_ABORTED 404 (Not Found)
(index):1203 GET http://localhost:53055/libs/reveal.js/3.8.0/js/reveal.js net::ERR_ABORTED 404 (Not Found)
(index):1208 Uncaught ReferenceError: Reveal is not defined
    at (index):1208
(anonymous) @ (index):1208
```

Does one need to first install `revealjs` with `npm` before using your plugin?

**Comment by evilz** [comment]
No you do not need this.

You are using Win10 right ?

**Comment by evilz** [comment]
I got it  !!! 
Everything is not working, in my case it was cause I open sample from cloned repo and `libs` is in same folder.

**Comment by evilz** [comment]
Just publish 4.0.2 🤞

**Comment by fuhrmanator** [comment]
4.0.2 looks good for Math and all the other things in the plugins part of the sample.md file. However, I'm not sure what is the "latest" sample.md, since the https://github.com/hakimel/reveal.js/ site [doesn't seem to provide one](https://github.com/hakimel/reveal.js/issues/2156). I suspect yours was reverse-engineered (by hand)?

**Comment by evilz** [comment]
It's mine just to test features
