### ISSUE TITLE
Cannot Show LaTeX matrix.

### ISSUE THREAD

**Issue by MoegiMugi** [evilz/vscode-reveal#220]
I tried to show LaTeX matrix in markdown, but I couldn't.
LaTeX code is this.
>$$
A=
\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22} + b_{ij}
\end{bmatrix}
$$

**Comment by evilz** [comment]
Should be fixed in next release

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.
