### ISSUE TITLE
Recurring [Math Processing Error]'s

### ISSUE THREAD

**Issue by LasseKrarup** [evilz/vscode-reveal#224]
Math seems to be rendered properly for some time, perhaps 5-10 seconds. Afterwards math starts switching quickly from correctly rendered to `[Math Processing Error]`. After some time the math area remains in `[Math Processing Error]` state.

Last test was with `$\pi$` and `$$\pi$$`. I've also tried `\\(\pi\\)`. Same result.

This happens both within the built in Chromium preview and in Google Chrome Stable Version 75.0.3770.80.

Information about my system:

**VS Code:**
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-21T12:30:20.933Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 4.19.45-1-MANJARO

**vscode-reveal**
vscode-reveal: 3.4.0

**Comment by evilz** [comment]
Do you have any sample to provide ? thank

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.
