### ISSUE TITLE
Feature request: custom override for browser path

### ISSUE THREAD

**Issue by drk-mtr** [evilz/vscode-reveal#245]
## Suggestion

Currently, the plugin attempts to set the browser path for us in the `BrowserHelper` file. This works for the vast majority of use cases, but for those using WSL it will fail.

It would be good if we could customise this path using a setting in `settings.json`, as this would allow users to either choose a browser themselves, or get it working on WSL.

While I'm here - THANK YOU for the fantastic plugin!

## Workaround

For anyone in a similar position, the workaround is to create a symbolic link from the path that vscode-reveal expects to the actual Chrome installation location in Windows e.g.
`ln -s "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" /usr/bin/google-chrome`

vscode-reveal still reports an error but the browser does start successfully.

**Comment by evilz** [comment]
Hi,

It should already works https://github.com/evilz/vscode-reveal/blob/master/src/Configuration.ts#L72

So you can set this in your setting or in md file directly.

Sorry for my late answer :(

**Comment by drk-mtr** [comment]
I feel rather silly now ha. Thanks for the help - much appreciated!
