### ISSUE TITLE
Upgrade to revealjs 3.8.0 and various package updates

### ISSUE THREAD

**Issue by damageboy** [evilz/vscode-reveal#248]
Hi @evilz,

I'm not sure if you are still developing this extension or can devote time to it.

I've made a fork / branch where I've upgraded various dependencies and mostly moved over to revealjs 3.8.0 as part of trying to "get into" this extension and maybe fixing some of the export bugs that people are encoutering (including myself).

Would it be OK for me to submit a PR and for you to review it?

Would you be interested?

**Comment by evilz** [comment]
Yes. It would be amazing

Make the PR I will look at it as soon I can

**Comment by damageboy** [comment]
Great!

I'm trying to get the whole thing packed with webpack (per the new recommendations), and it's not going so well in that respect (the 3.8.0 update seems ok...).

If I don't get it resolved by tomorrow, I'll just submit it without the webpack portion

**Comment by evilz** [comment]
not understand ?
I want to add Webpack too 👍 

Revealjs should not be a problem seen I do not use the npm package anymore

**Comment by damageboy** [comment]
The revealjs part was indeed easy :)

Webpack currently fails with a cryptic error, We'll get over it, one way or another :)
