### ISSUE TITLE
How to set the align as “ left” ？

### ISSUE THREAD

**Issue by hhhparty** [evilz/vscode-reveal#267]
In some presentation，such as the one with lots of words，the default align setting is  “center” and it isn't suitable. How can i set the align as "left" or "right" ?

**Comment by evilz** [comment]
https://github.com/evilz/vscode-reveal/blame/master/sample.md#L587-L591

**Comment by sisyphus1212** [comment]
::: {style="text-align: left;}
应对策略：

* 指令陷阱和模拟
* 二进制翻译
* 硬件辅助虚拟化改进
{style=font-size:0.7em}
:::

**Comment by sisyphus1212** [comment]
## 问题引入{style="text-align: left;}
