### ISSUE TITLE
Allow to disable custom explorer view on startup

### ISSUE THREAD

**Issue by spywhere** [evilz/vscode-reveal#27]
Every time a new project is opened, this extension will create a custom explorer view. VSCode allow users to hide custom explorer views out of the box. However, doing this hiding stuffs on multiple projects is quite tedious. By allowing users to disable custom explorer view at all help reduce these kind of task a lot.

I don't see if VSCode already provide an option to disable any custom explorer view by default (https://github.com/Microsoft/vscode/issues/34557). So that's why I open this issue.

**Comment by evilz** [comment]
Hi, 

you can hide it by workspace I think. Not sure, but I think it's store in .vscode folder.

**Comment by spywhere** [comment]
Correct, it can be applied per workspace, but what I want is make it to be globally applied (on all workspaces).
