### ISSUE TITLE
How to use exported HTML presentation

### ISSUE THREAD

**Issue by bask0** [evilz/vscode-reveal#275]
I can create a presentation with the extension, everything works fine. However, I do not know how to use the generated presentation, exported to HTML.

- I tried to open the exported index.html file in a browser; does not work. When I change the path of the markdown file in `index.html`, from `/markdown.md` to `markdown.md`, the content is displayed but without any styles and image links are broken.
- I tried to host the presentation on gihub using github pages, does not work.

I do not understand much of web development, I think I am missing something here. Can you tell me how to use the presentations on a computer that has no vscode with the vscode-reveal extension or how to host the presentation to access it remotely? What is your workflow?

**Comment by evilz** [comment]
At this time you need to use a web server and to open it on kind of localhost.

In next release, very soon it will not be necessary any more !!! \o/

**Comment by bask0** [comment]
Cool, looking forward to the release.
