### ISSUE TITLE
Allow configuration of google chrome path

### ISSUE THREAD

**Issue by draptik** [evilz/vscode-reveal#28]
Thanks for writing this very useful plugin!

On one of my machines running arch linux I use "Chromium" instead of "Google Chrome". Currently the path is hardcoded in file ChromeHelpers. Is it possible to make the path configurable in the future?

Workaround (in case anybody has a similar issue):

```
sudo ln -s /usr/bin/chromium /usr/bin/google-chrome
```

**Comment by evilz** [comment]
Thank for the work around ! 

I've got the same issue on x86 linux.

I'm going to do this 👍
