### ISSUE TITLE
4.0.2 is regressing on my presentation, 3.4.x worked fine

### ISSUE THREAD

**Issue by damageboy** [evilz/vscode-reveal#291]
Hi,
I'm experiencing a major regression with 4.0.2 with an existing presentation.

The previous presentation displays well and fine, but with 4.0.2 I just get a blank page:
![image](https://user-images.githubusercontent.com/125730/65391186-dae39600-dd6e-11e9-976a-22f6773240f0.png)

This is how it looks with 3.4.0:
![Screenshot from 2019-09-22 09-07-00](https://user-images.githubusercontent.com/125730/65383084-6120bd80-dd18-11e9-8164-0e34747b8a3a.png)

The presentation is abailable at:
https://github.com/damageboy/damageboy.github.io/tree/dev/talks/intrinsics-dotnetos-2019

The file is `intrinsics.md`

**Comment by fuhrmanator** [comment]
I found one problem with how images are loaded. Previously (3.4.x) this worked: 

```
<!-- .slide: data-background="images/myImage.jpg" data-background-opacity="0.2"-->
```

In 4.0.2 if you don't have a blank space before the closing comment `-->` this code is ignored. 

So, a working (in 4.0.2) example is:

```
<!-- .slide: data-background="images/myImage.jpg" data-background-opacity="0.2" -->
```

**Comment by evilz** [comment]
Thank for reporting this

**Comment by damageboy** [comment]
Hi @evilz,

Unfortunately 4.0.3 is still showing a blank page for me on:

https://github.com/damageboy/damageboy.github.io/tree/dev/talks/intrinsics-dotnetos-2019

Is there something I ould need to change?
