### ISSUE TITLE
4.0.2 export static html -> presenter mode not working 

### ISSUE THREAD

**Issue by worksasintended** [evilz/vscode-reveal#292]
Pressing S in exported html results in file not found error. 
Can be tested using the sample.md provided from repo.

**Comment by fuhrmanator** [comment]
S works in "Open presentation in browser"

**Comment by worksasintended** [comment]
Still not working for static export, notes.js not included in export

**Comment by fuhrmanator** [comment]
I just did this in 4.0.2 and the notes.js is in `export/libs/reveal.js/3.8.0/plugins/notes`. I didn't test today with a web server, but I did when I made my comment a week ago where I tested with the <kbd>S</kbd> key.

![image](https://user-images.githubusercontent.com/7606540/65967963-7f7d6c00-e430-11e9-97d8-d75898d0a6cd.png)

Do you have a more detailed error in the console of a browser that shows the missing support? A developer's tool (browser) will usually let you see all the .js files that were loaded.

**Comment by worksasintended** [comment]
Just to make sure again: the issue only occurs after static export.
```my-domain.com/libs/reveal.js/3.8.0/plugin/notes/notes.html
The requested document was not found on this server. 
```
The folder contains notes.js, but no notes.html
```
[libs]$ find . | grep notes
./reveal.js/3.8.0/plugin/notes
./reveal.js/3.8.0/plugin/notes/notes.js
```
It is working with open presentation in browser.

**Comment by evilz** [comment]
It's a issue, I forget to request the note page

**Comment by evilz** [comment]
It it OK in 4.0.3 ?

**Comment by worksasintended** [comment]
Works perfectly fine now! Thank you!
