### ISSUE TITLE
vertical slide: cant use mouse to change slide down

### ISSUE THREAD

**Issue by worksasintended** [evilz/vscode-reveal#307]
In both chromium and firefox it seems impossible to use the mouse to navigate down. Top, left, right work as expected.

**Comment by worksasintended** [comment]
Error only occurs sometimes, also there is no hover effect shown for this button. 
It looks like its blocked by the footer.

**Comment by evilz** [comment]
You mean arrow on bottom right

**Comment by worksasintended** [comment]
Right, it works if footer is deactivated but gets blocked by it if active.

**Comment by evilz** [comment]
Not really a bug in my code. So I close this issue. sorry
