### ISSUE TITLE
Can the width argument to Reveal.Initialize() be set from the frontmatter or custom css?

### ISSUE THREAD

**Issue by a-mckinley** [evilz/vscode-reveal#309]
Ideally would like to be a larger slide width than 960px.

**Comment by evilz** [comment]
Oh I did no know about that. 
I can add a parameter

**Comment by aminevsaziz** [comment]
@evilz @a-mckinley  any update on this topic. I have been searching the whole day but I didn't understand how to change for example the width using custom CSS or frontmatter. The owner of reveal.js said that Reveal.Initialize() is used to set values but how to achieve that in this case as i want for example 0 margins and 2x maxScale.

**Comment by fuhrmanator** [comment]
In the YAML I link to

```
customTheme: "my_themes"
```

In `my_themes.css` I have the following that will override (I think) the values (I verified in Chrome's inspector that it overrides the default `width:960`):

```
.slides div {
    width:100%;
    height: 100%;
}
```

**Comment by evilz** [comment]
Size is now an option in https://github.com/evilz/vscode-reveal/releases/tag/release%2F4.1.1
