### ISSUE TITLE
It can't find my chrome

### ISSUE THREAD

**Issue by leiserfg** [evilz/vscode-reveal#31]
Every action that requires chrome throws:
Can find Chrome on your computer, try with default browser... 
But:
$ which google-chrome
/usr/bin/google-chrome

and xdg-open works

**Comment by evilz** [comment]
Thank for reporting this.

What Linux do you use ? Is it in x64 ?

**Comment by leiserfg** [comment]
Manjaro.

**Comment by fesoliveira014** [comment]
I submitted a pull request fixing this issue. #34

**Comment by evilz** [comment]
@leiserfg @fesoliveira014  is it ok in news version (2.0.3) ?

**Comment by leiserfg** [comment]
Yes it's.
