### ISSUE TITLE
Reveal js server is started for every markdown file

### ISSUE THREAD

**Issue by mracos** [evilz/vscode-reveal#315]
Hi! First of all tks for this awesome extension. ❤️

I was rather surprised when I opened some random `README.md` and the `reveal-js` server was started. Would be nice if it was only started for `reveal-md` files (but we know that would be rather complex 😅) so I thought of some alternatives:

- Have a configuration like `autoStartRevealJsServer` that would be `enabled` by default and a command to manually start the server if desired
- Have a prompt to start the server when the user opens a markdown file

WDYT? Makes sense?

**Comment by fuhrmanator** [comment]
Related to #649

**Comment by evilz** [comment]
Fixed in [4.1.0 ](https://github.com/evilz/vscode-reveal/releases/tag/4.1.0)
