### ISSUE TITLE
Using static export HTML 5 (using with GitHub pages) - when are exported files generated?

### ISSUE THREAD

**Issue by fuhrmanator** [evilz/vscode-reveal#335]
I managed to get GitHub pages to work with the HTML5 exported files documented at https://github.com/evilz/vscode-reveal#htmlexport -- this is a great thing because you can deploy the HTML5 exports to the web. 

Here's how to make it work:

 - Change the VSCode extension setting `"revealjs.exportHTMLPath": "./docs"` instead of default `./export`
 - Change the GitHub repository setting to use `master branch /docs folder`
   ![image](https://user-images.githubusercontent.com/7606540/67495810-7ce5ef00-f649-11e9-9316-11d18f7e5cbb.png)

However, I was confused as to when the HTML5 exports get updated. Is it every save of the `.md` file? Or do I have to click on the `Revealjs: Export in HTML` button ![image](https://user-images.githubusercontent.com/7606540/67496212-11505180-f64a-11e9-98a6-d97c6bd20d71.png)
each time?

Is that button a toggle switch (turn on/off exporting on each save)? If it is, then there needs to be a better GUI feedback I think.

**Comment by evilz** [comment]
That's a button click so you need to click each time you want to export.
