### ISSUE TITLE
Question: The Slides Navigator does not show up in the Side Bar

### ISSUE THREAD

**Issue by desmond-dsouza** [evilz/vscode-reveal#348]
Is there something I need to do to display it?

**Comment by evilz** [comment]
Just having a markdown file should be enought

**Comment by desmond-dsouza** [comment]
Retried a couple of times, see picture. Any suggestions?
![image](https://user-images.githubusercontent.com/4407158/68088555-03f34e00-fe26-11e9-84b7-cd1737e0d810.png)

**Comment by evilz** [comment]
It's not in explorer anymore you should have a menu on left

Le dim. 3 nov. 2019 à 17:39, desmond-dsouza <notifications@github.com> a
écrit :

**Comment by desmond-dsouza** [comment]
Thank you!
