### ISSUE TITLE
Mermaid rendering in VS preview but not on export

### ISSUE THREAD

**Issue by rahul-psych** [evilz/vscode-reveal#349]
Hi all,

Trying to embed mermaid gantt charts and flow charts in a presentation. The Gantt renders beautiful in the side preview within VS code though the labels are misaligned in flowcharts. 

When exported, the labels don't appear in the flow chart boxes and the gantt chart doesn't render at all (tested on Opera, Chrome, FF and Edge) and flow chart missing labels entirely in Opera, Chrome & edge and not rendering at all in FF. 

PS: Others *love* the extension. Thanks!

**Comment by evilz** [comment]
you can do that in v4.1.0

````
    ---
    theme: white
    ---
    
    ```mermaid
    classDiagram
          Animal <|-- Duck
          Animal <|-- Fish
          Animal <|-- Zebra
          Animal : +int age
          Animal : +String gender
          Animal: +isMammal()
          Animal: +mate()
          class Duck{
              +String beakColor
              +swim()
              +quack()
          }
          class Fish{
              -int sizeInFeet
              -canEat()
          }
          class Zebra{
              +bool is_wild
              +run()
          }
    ```
```
