### ISSUE TITLE
How do I change the width or height of the slides?

### ISSUE THREAD

**Issue by desmond-dsouza** [evilz/vscode-reveal#356]
Either in front-matter or in a css file would work. Thanks!

**Comment by evilz** [comment]
??

**Comment by desmond-dsouza** [comment]
Sorry I was not clear! Is there a way to change the width or height of the slides? Does it go into front-matter YAML directly? Or into a css file that is referenced in the front-matter YAML? Thanks!

**Comment by evilz** [comment]
You can set it using revealjs.theme parameter in Vs code config or in the document itself using front matter.

If you want a custom theme you can do it! Just add custom style to a CSS file in the same folder that your markdown.

example: if your file name is my-theme.css just add this in the front matter header :

```
---
customTheme : "my-theme"
---
```

Note that you can use both theme and custom theme at the same time. Your custom theme will be loaded after to override default reveal.js theme.
