### ISSUE TITLE
How exactly do you use this?

### ISSUE THREAD

**Issue by Jakobud** [evilz/vscode-reveal#37]
Where are the instructions? Do you make a markdown file? Or an html file?

I create a markdown file and run the command:

> Reaveljs: Open presentation in browser

and I get the notification:

> Command: vscode-revealjs.showRevealJSInBrowser not found

I get similar notifications for every RevealJS command.

The documentation seems to have a ton of information about the details of the different options and commands and stuff, but it has almost no info on how to actually get started. Do you have to install reveal.js locally in your HTML?

#confused.

**Comment by Jakobud** [comment]
This doesn't seem to work as far as I can tell. 

First of all, how exactly do you get the Slides sidebar to show up? After experimenting what I've found is if I open a new workspace folder, then create a file called `slide1.md`, then the slides sidebar shows up all the sudden. Is that how you are supposed to do it?

Next, when I start creating multiple slides, only one slide shows up in the sidebar, and it's called `0`. The file contents change when I activate different slides.

<img width="1033" alt="screen shot 2018-04-30 at 8 58 13 am" src="https://user-images.githubusercontent.com/87356/39434123-ec5b7558-4c54-11e8-9b67-732f62c9c9eb.png">

Still really confused on how to use this thing. Just getting the slides sidebar to show up seems like it's buggy or something. I have no idea what determines or controls when that sidebar should be visible or not.

**Comment by Jakobud** [comment]
Okay okay I think I figured this out. Everything goes in a single markdown file. Slides are separated using `---` and basement slides are separated using `--`. That is key information you guys need to have in your instructions. Took me forever to figure this out.

**Comment by evilz** [comment]
Readme is the doc and there is a sample here https://github.com/evilz/vscode-reveal/blob/master/sample.md
