### ISSUE TITLE
Can we customize CSS?

### ISSUE THREAD

**Issue by markheath** [evilz/vscode-reveal#4]
I'd like to override a few of the CSS rules in the reveal theme css

e.g. I'd like to do things like turn off `text-transform: uppercase;` for headings change the color of inline code by adding a rule like     `.reveal code { color: aquamarine; }` etc

Is there already a way to accomplish this?

If not, could there be a way to insert a special command in the markdown that points at a CSS file of customizations to get copied as part of the presentation.

thanks

**Comment by evilz** [comment]
Hi,

The short response is : **not yet**.

I will add this feature in future release.
You will give a custom css file path.

If you really need to do this by now, you can edit css in folder extension by yourself.

**Comment by evilz** [comment]
Add `customTheme` in front matter
