### ISSUE TITLE
Option for offline MathJax

### ISSUE THREAD

**Issue by mmlanger** [evilz/vscode-reveal#40]
First of all, thanks for this amazing extension! It's just so convenient!

While it is very easy to set the path to the default browser, It seems that it's not straightforward to change the location of mathjax, e.g. for offline use. At least as far as I know reveal.js loads mathjax from an online source, but I do have sometimes limited connection and like to create presentations with math rendering nonetheless.

Is there an easy way to change the mathjax path and I just missed it?
Could you add this as an option if it is not yet included?

**Comment by evilz** [comment]
Ok, thank I just understand the problem.

I need to make this

```js
Reveal.initialize({
	// other options ...

	math: {
		mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js',
		config: 'TeX-AMS_HTML-full'  // See http://docs.mathjax.org/en/latest/config-files.html
	},

	dependencies: [
		{ src: 'plugin/math/math.js', async: true }
	]
});
```

works.

I starded to think about a solution for redifine all this if needed.

Thank again

**Comment by evilz** [comment]
For this case maybe :)

**Comment by evilz** [comment]
Should be good #102
