### ISSUE TITLE
Wrong ordering when uncovering list fragments using Markdown

### ISSUE THREAD

**Issue by pohlt** [evilz/vscode-reveal#407]
# Versions

* Manjaro Linux 5.5.0, 64 bit
* vscode-reveal 4.0.3
* Chrome 78

# Example

Given the following example:
```markdown
# Fragment Test

Some text before.

* A <!-- .element: class="fragment" -->
* B <!-- .element: class="fragment" -->
* C <!-- .element: class="fragment" -->
* D <!-- .element: class="fragment" -->

Some text after.
```
## Expected Behavior
The unstructured list items are uncovered as A, B, C, D.

## Actual Behavior
The unstructured list items are uncovered as D, A, B, C.

## Observations

The generated HTML looks like this:
```html
<ul class="fragment visible" data-fragment-index="0">
    <li class="fragment visible" data-fragment-index="1">A </li>
    <li class="fragment visible" data-fragment-index="2">B </li>
    <li class="fragment visible current-fragment" data-fragment-index="3">C </li>
    <li>D </li>
</ul>
```
This explains the wrong ordering, but I don't know how to correct the Markdown text to get the desired result.

Maybe I'm just using the fragment notation in a wierd way. Thanks anyway.

**Comment by evilz** [comment]
Try to not write Space before the comment

**Comment by pohlt** [comment]
You mean like this?
```markdown
* A<!-- .element: class="fragment" -->
* B<!-- .element: class="fragment" -->
* C<!-- .element: class="fragment" -->
* D<!-- .element: class="fragment" -->
```
Still the same issue. :-(
Thanks anway.

**Comment by jjrsylvestre** [comment]
I have the same issue. Manually editing the exported HTML to move the
`class="fragment"`
attribute from the ul or ol down to the last li gives the desired behaviour.

**Comment by evilz** [comment]
You can do this 

````markdown
# Fragment Test

Some text before.

* A{.fragment}
* B{.fragment}
* C{.fragment}
* D{.fragment}

Some text after.
```

**Comment by pohlt** [comment]
Awesome - you rock!
