### ISSUE TITLE
plantuml

### ISSUE THREAD

**Issue by czhiling** [evilz/vscode-reveal#428]
I am new to reveal.js and viscose-reveal. I was searching for using plantuml with viscose-reveal but no luck. 

viscose-reveal supports mermaid. However plantuml is more powerful and is keeping upgraded. 
I was trying to use reveal-plantuml plugin but I did not know how to add it.

**Comment by fuhrmanator** [comment]
This would be very cool. But I'm not sure how stable that plug-in will be, or how much effort it is to integrate it.

For now, I use the PlantUML extension in VSCode to generate URLs (markdown) from PlantUML source, and put that in my markdown. But it's too many steps. I suggested a feature at https://github.com/qjebbs/vscode-plantuml/issues/280 - the cool thing about that extension is that it doesn't care where your PlantUML source is.

**Comment by evilz** [comment]
In version 4.1.0

```
    ---
    theme: white
    ---
    
    ```plantuml
    @startuml
    Alice -> Bob: Authentication Request
    Bob --> Alice: Authentication Response
    
    Alice -> Bob: Another authentication Request
    Alice <-- Bob: Another authentication Response
    @enduml
    ```
```
