### ISSUE TITLE
Request: Publish Extension on open-vsx.org for GitPod

### ISSUE THREAD

**Issue by HansUXdev** [evilz/vscode-reveal#527]
I was wondering if you'd be willing to collaborate to publish it to open-vsx instead of just the vs code marketplace. 

Currently, the extension is available on the Microsoft VS Code marketplace.
VS Codium (VS Code without MS telemetry, the link for more details: https://github.com/VSCodium/vscodium/blob/master/DOCS.md) uses the open-vsx.org marketplace (Eclipse Foundation) instead. This has an adapter for MS VS Code Marketplace, but currently, your extension is not available in VS Codium using open-vsx. Would it be possible for you, to post the extension also to open-vsx.org? Alternatively, the extension could be added here: https://github.com/open-vsx/publish-extensions. They would then publish it in a nightly run.

**Comment by evilz** [comment]
Thank fot telling me !
I will take a look

**Comment by HansUXdev** [comment]
Yeah let me know if you need help because I want to use your extension for slides on my coding educational content and having it available in GitPod would be awesome.

**Comment by HansUXdev** [comment]
🎉Sweet, I just published it for you.🎉
https://open-vsx.org/extension/evilz/vscode-reveal

You can now do presentation in remote. However it should be noted that the sidebar doesn't up. 
I believe it's a gitpod configuration issue and you just need to click the button in the photo.

<img width="1399" alt="Screen Shot 2020-08-30 at 3 51 16 PM" src="https://user-images.githubusercontent.com/5007073/91671133-adec4700-ead8-11ea-9fd0-9e8d28d1398e.png">

**Comment by evilz** [comment]
❤💙💚💛💜

**Comment by totoroot** [comment]
@HansUXdev @evilz Any reason why the extension is no longer available under [https://open-vsx.org/extension/evilz/vscode-reveal](https://open-vsx.org/extension/evilz/vscode-reveal)?
I tried installing it today from directly within VSCodium, but the extension could not be found.
I could download the vsix file from the [visual studio marketplace](https://marketplace.visualstudio.com/items?itemName=evilz.vscode-reveal) and import it, but I am curious as to what could be the reason why it's no longer available on the open-vsx.org marketplace...
Any information on this?

**Comment by evilz** [comment]
DONE 🎉
