### ISSUE TITLE
Menu and AutoPlay overlap

### ISSUE THREAD

**Issue by HansUXdev** [evilz/vscode-reveal#529]
Is there a way to prevent the autoplay button and the menu from overlapping without a full custom theme override?

<img width="954" alt="Screen Shot 2020-08-14 at 9 40 43 AM" src="https://user-images.githubusercontent.com/5007073/90272446-4bc1ef80-de12-11ea-934c-3445e96fc2e3.png">

**Comment by evilz** [comment]
Revealjs related
