### ISSUE TITLE
FR: Page title in YAML

### ISSUE THREAD

**Issue by mzed** [evilz/vscode-reveal#55]
I would like to be able to set the page title in the YAML front matter. Something like:

```
title: "My presentation"
```
Would be great.  I realize that this is (obviously) not a RevealJS option, and might not be the easiest thing to implement.

**Comment by evilz** [comment]
Hey, you right it should be add !
Not so hard to do I think.

**Comment by mzed** [comment]
Thanks! Also, thank you for the plugin. It's very useful.

**Comment by evilz** [comment]
'title' Can now be set in front  #102
