### ISSUE TITLE
vscode-reveal does not work properly in jupyter notebooks for the insiders edition

### ISSUE THREAD

**Issue by hugocool** [evilz/vscode-reveal#605]
version:
vscode insiders 1.53

expected behaviour:
when adding multiple markdown cells and code cells to a jupyter notebook, these cells should be added to the overview of the slides on the left pane.

actual behaviour:
only the currently selected markdown cell is added to the presentation, and code cells/output are not added

**Comment by evilz** [comment]
nothing to do with jupyter ^^
