### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by olusams** [evilz/vscode-reveal#636]
- Issue Type: `Performance`
- Extension Name: `vscode-reveal-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\User\AppData\Local\Temp\evilz.vscode-reveal-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by evilz** [comment]
No news ...
