### ISSUE TITLE
Consistent behavior with root folder for the localhost server

### ISSUE THREAD

**Issue by fuhrmanator** [evilz/vscode-reveal#649]
There are times when I start up VSCode on a vscode-reveal markdown project (Workspace) where the localhost server uses the workspace folder as root, and other times it uses a different folder as root. I think I finally figured it out.

For example, here's a sample workspace:
```
folder
  presentation.md
  favicon.ico
test.md
```

If I have VSCode stopped, and open the Workspace above, the root folder for localhost will depend on which `.md` file is opened first.

If I first open `test.md` then the web server won't know to look in `folder` for the `favicon.ico` (makes sense). On the other hand, if I close all the `.md` windows and restart VSCode, then open `folder/presentation.md`, the root folder becomes `folder/` and so the icon works. This is a problem also for any folders of images reused among presentations; the favicon.ico example is a simple one.

I'm not sure this behavior is a bug per se, but it's sometimes confusing if you don't understand the behavior. 

I'm not sure if it's possible, but it would be consistent if the web server could use the workspace folder as root. Otherwise, in such projects it's necessary to make symbolic links or copy the files around. 

Edit: stopping the web server (red box on the bar at the bottom) and restarting it by opening a different markdown file doesn't change the root folder on my version. I have to quit VSCode after closing all the `.md` files.

**Comment by evilz** [comment]
It should launch on server (port) by presentation 🤔

**Comment by evilz** [comment]
Fixed in 4.1.0
