### ISSUE TITLE
Icons of slides are not visible

### ISSUE THREAD

**Issue by SR--** [evilz/vscode-reveal#711]
![image](https://user-images.githubusercontent.com/1008059/133784954-3d69924c-1344-4e11-a4bb-4484002dd8b9.png)

**Comment by evilz** [comment]
Thank for report this issue. 
Maybe something had changed in VS code 🤔

**Comment by SR--** [comment]
Yes, likely. By the way, thanks for the extension, just trying it out but loving it so far.

**Comment by SR--** [comment]
@evilz Thanks again for replying. From this, it looks like the PREVIEW version shows the icons fine, in case this can be helpfu. https://github.com/tokiedokie/reveal-markdown/issues/23

Generally, any chance for the update to the latest reveal.js and merging back of the preview and fork versions? Cheers.

**Comment by evilz** [comment]
Fixed in [4.1.0 ](https://github.com/evilz/vscode-reveal/releases/tag/4.1.0)
