### ISSUE TITLE
[question] Image Styling

### ISSUE THREAD

**Issue by SR--** [evilz/vscode-reveal#712]
How can I remove the border, shadow, etc. from all images?

This in the Markdown works:
`<img src="/assets/images/test.png" width="40%" style="border: 0; background: None; box-shadow: None">`

This in CSS partially works. I can curve the corners but not set the border to 0 or change its colour.

`
img {
  border: 2px solid red;
  border-radius: 8px;
  width: 200px;
}
`
![image](https://user-images.githubusercontent.com/1008059/133795529-c021b6d3-d779-48f0-9f20-f010b7634fbb.png)

Any tips?

**Comment by SR--** [comment]
Never mind, forced it with the '!important' control.

**Comment by evilz** [comment]
Good solution 👍
