### ISSUE TITLE
Support AsciiDoc syntax

### ISSUE THREAD

**Issue by stenzengel** [evilz/vscode-reveal#73]
Hi Vincent,

Thanks for your VS Code extension. Are there any chances, that your extension also supports AsciiDoc syntax?
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/README.adoc

I switched from Markdown to AsciiDoc, because of all the different and limited Markdown flavors:
https://asciidoctor.org/docs/asciidoc-vs-markdown

Thanks,
Winfried

**Comment by evilz** [comment]
Hi, 

Actually not, you are the first one to mention this. 

sorry
