### ISSUE TITLE
reveal-md backend

### ISSUE THREAD

**Issue by svenkreiss** [evilz/vscode-reveal#74]
I have a workspace with `reveal.json` and `reveal-md.json` and a custom theme folder (replaces MathJax with KaTeX in html template plus custom CSS). Is there a way to use this extension in combination with reveal-md as backend and still get synced slide preview inside of vscode?

**Comment by evilz** [comment]
Hi,

This extension is not using 'reveal-md'.

Actually it's not possible to change the html template.

Maybe it can be usefull.
