### ISSUE TITLE
Slide separator in 4.1.0 extension

### ISSUE THREAD

**Issue by scottstaffiere** [evilz/vscode-reveal#740]
I've been using this extension for a while and really like it.  I noticed that after the extension was upgraded to 4.1.0, my custom slide separators no longer work and it shows as a single slide.  In the meantime, I downgraded.

Here is a basic test case which works on 4.0.3, but not 4.1.0.

```
---
title: Test
separator: <!--s-->
verticalSeparator: <!--v-->
theme: black
customTheme: custom
transition: 'slide'
enableChalkboard: false
enableTitleFooter: false
enableMenu: false
revealOptions:
    transition: 'slide'
---
# Test

<!--s-->
### Slide 1
Content

<!--s-->
Slide 2

<!--v-->
Vertical Slide

```

**Comment by evilz** [comment]
Your Right. I removed this parameters that make code more complex and harder to maintain.

The question is do you really need this ?

Why 

`---`

And 

`--`

Are not enough?

**Comment by scottstaffiere** [comment]
Thanks for the quick response.  I used to use [this framework](https://github.com/webpro/reveal-md) to generate my presentations.  I just got into the habit of using some of their examples with `<!--s-->` and `<!--v-->` in all my presentations since s and v were much more intuitive than 3 and 2 dashes.  When I found your plugin last year, I was happy to find that it worked pretty much exactly the same way and I could just keep continuing on with what I was familiar with.  When the plugin updated, all my presentations broke and it thought I only had 1 slide.  

So to answer your question, it would be great if the same functionality continued to work.  But I also don't maintain the code and realize it's probably not worth the effort if there is a workaround.  It just means that I would need to just go through all my presentations and update the separators.  I'm fine with doing that if you made a conscious choice to slim down the codebase.  I just wanted to make sure it wasn't an unintended bug.

**Comment by IamTHEvilONE** [comment]
I would add that for my use case, I'm just a writer and have no control over the reveal.js deployment/config IT provides.  They customized and used --h-slide-- and --v-slide-- in their implementation.  My team of 4 had to roll back for just this reason since the parameter is no longer available in 4.1.

**Comment by evilz** [comment]
I use custom separators :

/polls YES NO

**Comment by evilz** [comment]
Release in 4.1.2

**Comment by IamTHEvilONE** [comment]
In 4.1.2, I can enable the custom separator using the meta method:

---
separator: --h-slide--
verticalSeparator: --v-slide--
---

But it don't see the same options a 4.0.3 had to store the settings in the Extension ... which is why I still use 4.0.3 despite 4.1.2 being released.
