### ISSUE TITLE
Presentation size

### ISSUE THREAD

**Issue by sylefeb** [evilz/vscode-reveal#741]
Hi - I am greatly enjoying vscode-reveal. I'd like to change the presentation aspect ratio, which I believe is 4:3 currently. I see from the [reveal.js documentation](https://revealjs.com/presentation-size/) that there are settings for this, but I could not find how to edit them from vscode-reveal.

If that is not yet possible, I am happy to hear about any workaround. I am very new to reveal.js, so I hope I am not missing something obvious ...

Thank you!

**Comment by evilz** [comment]
Yes you'r right 

I need to add this config settings.

**Comment by sylefeb** [comment]
Fantastic, thank you. Tested and working!
