### ISSUE TITLE
upgrade to reveal.js 3.7

### ISSUE THREAD

**Issue by dezGusty** [evilz/vscode-reveal#79]
Hi there,

Reveal.js v 3.7 brings the new  [Key Bindings API](https://github.com/hakimel/reveal.js#custom-key-bindings). This allows the users (well... me at least) to more easily hack `Template.js` and add a custom script to allow local plug-ins (stored side by side with the `.md` files) by configuring part of them post-initialization.

E.g.
```js
function setCustomKeys() {
  // clear chalkboard when 'DEL' is pressed
  Reveal.addKeyBinding( 46, function() {
    RevealChalkboard.clear();
  });
  // reset chalkboard data on current slide when 'BACKSPACE' is pressed
  Reveal.addKeyBinding( 8, function() {
    RevealChalkboard.reset();
  });
}

window.onload = () => {
  setCustomKeys();
}
```

If you have some spare time, I would really appreciate a new release with updated dependencies.
Thank you,
dezGusty

**Comment by evilz** [comment]
I will do this :)

**Comment by evilz** [comment]
In fact revealjs is already in 3.7 in source code
https://github.com/evilz/vscode-reveal/blob/master/package-lock.json#L2399-L2403

I studding the best way to make a powerful and simple templating feature.

**Comment by dezGusty** [comment]
I'm not sure whether this helps or not, but the way in which I made it work for me was to add a configuration option named `postInitScript` (value: string; e.g. postinit.js) , which allows users to point to a file on the disk to add some custom initialization code. I updated the Template.js script. 

Any additions are in the local structure.

- `css\`
- `data\`
- `lib\`
- `plugin\`
- `webfonts\`
- `favicon.ico`
- `postinit.js`
- `myfile.md`

I typically start code in such a dir...
```cmd
code .
```

A gist of the sample [here](https://gist.github.com/dezGusty/d80851ecab617cd86ff67d260b2bc132)

Issues: 

- no checks for availability of source file (if the user sets the value to `js/xxx.js` and there is no such file, it breaks the plug-in (no display of the preview) . Perhaps it would be better to not have an option; but to have a fixed file name and location (e.g. js/postinit.js) and store it the vscode extension dir (would also require updating the express initialization in Server.js)
- not sure how to best add extra css files, such as `all.min.css`.
