### ISSUE TITLE
logoImg path?

### ISSUE THREAD

**Issue by SeaDude** [evilz/vscode-reveal#791]
Hello,

Where does vscode-reveal look for the `logoImg`?

**I tried:**

- Full path: `"E:\dataDocuments\ktree\vault\assets\images\pa_logo.png"`
- Image path (like when pasting images in Markdown): `"assets\images\pa_logo.png"`
    - `"\assets\images\pa_logo.png"`
    - `".\assets\images\pa_logo.png"`
    - `"assets/images/pa_logo.png"`

Thank you

**Comment by evilz** [comment]
Full path should work but maybe not display cause of security stuff of Vscode.

But everything is relatif to root folder of your MD file

**Comment by SeaDude** [comment]
Thank you for the clarification. 

This worked: `./assets/images/pa_logo.png`
