### ISSUE TITLE
exported presentation has localhost links

### ISSUE THREAD

**Issue by clux** [evilz/vscode-reveal#799]
i cannot find a setting that turns this into the correct relative path - thinking that should just work since all the 3rd party resources are included in the export folder.

e.g. export/index.html

```html
<link rel="stylesheet" href="http://localhost:43639/libs/highlight.js/11.3.1/styles/monokai.min.css">
```

this makes it hard to use with github-pages or similar (although it sometimes works accidentally when you have the reveal server running locally)

**Comment by clux** [comment]
i have a workaround for iterating and publishing now:

```sh
rm -rf docs/
cp export docs -r
sd  "http://localhost:45707" "/metrics" docs/index.html
```

i am probably missing something obvious here though :-)
thanks a lot for writing this extension!

**Comment by evilz** [comment]
It should not ,🤔 l'll take a look

**Comment by lsmith-kc** [comment]
I had the same issue. Now using a cleanup script after export.

```
#!/bin/sh 
# replaces references to 'localhost' with relative paths 
# to enable serverless presentations locally and on the web 
 
find ./index.html -type f -exec sed -E -i '' 's/http:\/\/localhost:[0-9]+\//.\//g' {} \; 
```

**Comment by gVallverdu** [comment]
I run into the same issue. But there is also something more about `data-background-image`.

Here are the issues, if I try to explain (I am not very skilled about server ...)

* I did a presentation in markdown and it displays very well in vscode. 
* If I copy/paste the link and look at the presentation in a browser it is ok, let's say `https://localhost:57795`
* Now I try to export the presentation as html file and open the `index.html` file in the browser. Two different things happen.

### First issue

If I shut down vscode or the presentation (the server, `https://localhost:57795`), on the browser, the presentation does not display correctly. But, as said in the previous comments, if you replace the `https://localhost:57795` by `""` or the baseurl of you web page. It works again.

### Second issue

The second issue is about `data-background-image`. Let's say you have the following markdown code:

```markdown
--

## a title

<!-- .slide: data-background="img/image.jpg" -->

--
```

 When you export the presentation as html, the produced html code is the following :

```html
<section data-background="img/image.jpg">
<!-- .slide: data-background="img/image.jpg" -->
<h2>a title</h2>
</section>
```

Whatever the state of the server in vscode, if you open the presentation from `index.html` in a browser, the background image is not displayed. Contrary to the previous solution, you have to add the `https://localhost:57795` url to make it works (assuming this server/address is still running in vscode). Actually it works (in all case) if you put, as background, a picture from an url but it does not work if you use a local file. That is why it works if you add the `https://localhost:57795` address.

**Comment by evilz** [comment]
Release in 4.1.2
