### ISSUE TITLE
Bug: can't open presentation in browser

### ISSUE THREAD

**Issue by fuhrmanator** [evilz/vscode-reveal#801]
When I open a folder with an existing presentation, select the markdown, then the "Open presentation in browser", nothing happens.

![image](https://user-images.githubusercontent.com/7606540/152394288-9d1e2691-1f4c-45ad-9222-5088f422274d.png)

The workaround is to first "show presentation by side", then it works. 

It seems like a bug. I'm using v.4.1.1.

**Comment by evilz** [comment]
Thank, I will take a look

**Comment by evilz** [comment]
Release in 4.1.2
