### ISSUE TITLE
Snippets are too invasive

### ISSUE THREAD

**Issue by codefoster** [evilz/vscode-reveal#815]
With `vscode-reveal` installed, when I'm in a markdown file and type `..` the snippets such as `.fullscreen` pop up and get in the way. In my opinion, `..` is not a specific enough lead-in to a snippet because I type that very often in markdown files. I may for instance type...

```
Some paragraph text...<enter>
```
...but in doing so, the snippet is invoked.

**Comment by evilz** [comment]
You are so right !

what about   `sld-fullscreen`   ? 

`sld-attributs` 

 ?

**Comment by codefoster** [comment]
@evilz, I don't understand what you're suggesting/asking.

**Comment by evilz** [comment]
Release in 4.1.2

**Comment by codefoster** [comment]
Excellent. Thank you, @evilz!
