### ISSUE TITLE
Feature request: preprocessor injection for slides

### ISSUE THREAD

**Issue by vittorioromeo** [evilz/vscode-reveal#820]
Hello,

I use a custom flavor of Markdown for some special slides that gets preprocessed into regular Markdown through a bespoke script (executable).

I would like to use your extension to work on those slides and have a live preview of the final result. I've actually achieved this goal by forking your process and hardcoding a `spawnSync` call right before the slides get sent to the preview window -- it works great.

I opened this issue to see if there's any interest in merging this functionality upstream, obviously as an optional flag that can be turned on on a per-need basis.

**Comment by evilz** [comment]
Any repo to see the code ?

**Comment by vittorioromeo** [comment]
> Any repo to see the code ?

This is the current *hack* I am using:
https://github.com/vittorioromeo/vscode-reveal/blob/master/src/RevealServer.ts#L107-L131

**Comment by evilz** [comment]
Sorry, I will not add this, at least not in this way.
I dont want to spawn some process. (only browser)
