### ISSUE TITLE
Control image location on slide?

### ISSUE THREAD

**Issue by SeaDude** [evilz/vscode-reveal#824]
Hello,

I'd like to control the locations of 3 different images on the same slide. 

I know I can use `<span>` or `<table>` tags to shown multiple images on a slide, but the images end up being in a line (vertical or horizontal). I need to place images in more organic locations. 

**How can this be done using HTML in this extension?**

**Comment by evilz** [comment]
Style or css should be the solution

**Comment by SeaDude** [comment]
Thank you. Do you have a rough example of how to do this?

**Comment by SeaDude** [comment]
Disregard ;) I think its something like this:

```html
<a href="http://www.TBD-URL.com/consumer-250×250.jpg" target="_blank"><img src="http://www.TBD-URL.com/consumer-250×250.jpg" style=" float:right; margin:0px 0px 15px 15px;cursor:pointer; cursor:hand; border:0" width="100" height="100" alt="Woman with child checking email" /></a>
```

Where `float:right` and `margin` will get the image where I want it.

[REF:](https://reinhartmarketing.com/support/images/html-image-position-code/)

**Comment by evilz** [comment]
or flex maybe can help also

**Comment by SeaDude** [comment]
**I ended up going with this (pretty ugly, but it works for my use-case)**:

```html
<img src="https://c.pxhere.com/photos/aa/f7/positive_be_positive_smile_smiling_happy_write_draw_symbol-736153.jpg!d" style="float:right; z-index: 3; position: relative;" height="200"/>

<img src="https://c.pxhere.com/images/47/0e/95831d1754d0b5f7eb270885646d-1451207.jpg!d" style="float:left; z-index: 2; position: relative;" height="200"/>

<a href="https://duckduckgo.com" target="_blank">
    <img src="https://c.pxhere.com/photos/5b/6e/poses_female_education_posing_caucasian_what_confused-804575.jpg!d" style="margin: 0px 0px 100px 100px; z-index: 1; top: -360px; position: relative;" height="550"/>
</a>
```

**Renders like:**

![image](https://user-images.githubusercontent.com/8636973/154172425-b88c1f73-58e2-46cc-9ffb-3d03198c2ee5.png)

**Comment by evilz** [comment]
Cool ! 

Note that you can use the short style markdown version

```
![](url){ style=float:right; z-index: 3; position: relative;height:200px" }

```
