### ISSUE TITLE
change the size of and image with tags.

### ISSUE THREAD

**Issue by vs2ds** [evilz/vscode-reveal#827]
is the following possible?

`![](my image.png) {height=100px}`

I paste image in my markdowns a lot. I need to resize them to make them fit inside my window. if there a way to add a tag around them and avoid HTML tags?

**Comment by evilz** [comment]
# I don't understand what you mean. Can you add screen shot

**Comment by fuhrmanator** [comment]
@evilz I'm not sure of the OP's exact question, but I do have an example based on the RevealJS documentation https://revealjs.com/layout/#stretch

This seems to work by resizing dynamically (you can try it):

```markdown
# Hello

- one item that is pretty long
- two items
  
<img class="r-stretch" src="https://c.pxhere.com/photos/5b/6e/poses_female_education_posing_caucasian_what_confused-804575.jpg!d">
```

However, trying it in pure markdown doesn't:

```markdown
# Hello

- one item that is pretty long
- two items
  
![](https://c.pxhere.com/photos/5b/6e/poses_female_education_posing_caucasian_what_confused-804575.jpg!d){.r-stretch}

```

The first example seems to render in the browser as

```html
<img class="r-stretch" src="https://c.pxhere.com/photos/5b/6e/poses_female_education_posing_caucasian_what_confused-804575.jpg!d" style="height: 344px; width: 497.949px;">
```

whereas the second renders inside a `<p>` like:

```html
<p><img src="https://c.pxhere.com/photos/5b/6e/poses_female_education_posing_caucasian_what_confused-804575.jpg!d" alt="" class="r-stretch"></p>
```

Indeed the difference makes it hard to use pure markdown to get the desired result with `r-stretch`. This issue has been raised before in #333

**Comment by evilz** [comment]
does this sample help ? 
https://github.com/evilz/vscode-reveal/blob/master/samples/layout.md

**Comment by fuhrmanator** [comment]
> does this sample help ? https://github.com/evilz/vscode-reveal/blob/master/samples/layout.md

Yes! The trick is one must leave white space before the `{.r-stretch}`. Your sample has a line-break, but it could also be a space. If there's no whitespace, the `<img>` is inside a `<p>` as shown in https://github.com/evilz/vscode-reveal/issues/827#issuecomment-1043159128 and the class doesn't work. I'm not sure if the whitespace issue is a bug or a feature, but at least it's documented here.

```markdown
## Stretch Example

![](https://revealjs.com/images/slides-symbol-512x512.png)
{.r-stretch}
```
