### ISSUE TITLE
Code highlight line numbers animation not working

### ISSUE THREAD

**Issue by elonmallin** [evilz/vscode-reveal#836]
It doesn't seem possible to highlight certain lines and line ranges like this: https://revealjs.com/?demo#/5/0/0
The below example should highlight line 1 then lines 3-5 and then go to the next slide but it skips that and reads it as just one slide.

```markdown
## Code example

```javascript [1|3-5]
const name = 'Name'

const greeting = (name) => {
    console.log('Hello', name)
}

greeting(name)
```
```
```

This works if you do the full setup of revealjs locally https://revealjs.com/installation/#full-setup and add this to the body:
```html
<div class="reveal">
<div class="slides">
<section data-markdown>
	<textarea data-template>
		## Code example
		```javascript [1|3-5]
		const name = 'Name'

		const greeting = (name) => {
			console.log('Hello', name)
		}

		greeting(name)
		```
	</textarea>
</section>
</div>
</div>
```

**Comment by evilz** [comment]
do it like this 

```
```js {data-line-numbers="1|3-5|7"}
const name = 'Name'

const greeting = (name) => {
    console.log('Hello', name)
}

greeting(name)
` ```
```

**Comment by fuchse-ego** [comment]
Hi,
great plugin. I also stumbled upon this as it was not working. Is it possible to update the full documentation?
I also found the example in the sample.md did not highlight the code for me.
