### ISSUE TITLE
customTheme not recognized in v4.1.2

### ISSUE THREAD

**Issue by GrumpyLabRat** [evilz/vscode-reveal#849]
A presentation that was created in 4.1.1 now defaults to the black theme.  No changes were made to the presentation between the release of 4.1.1 and 4.1.2.  Rolling back to 4.1.1 returns the ability to use a customTheme.

**Comment by evilz** [comment]
You mean the default theme has changed,🤔

**Comment by GrumpyLabRat** [comment]
No it’s not recognizing the “customTheme” command in the front matter of the presentation:  Ignore the QRImg code.  That is related to issue #848.  From: Vincent B. ***@***.***>Date: Wednesday, March 9, 2022 at 2:50 PMTo: evilz/vscode-reveal ***@***.***>Cc: GrumpyLabRat ***@***.***>, Author ***@***.***>Subject: Re: [evilz/vscode-reveal] customTheme not recognized in v4.1.2 (Issue #849)You mean the default theme has changed,🤔—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by evilz** [comment]
it's working for me on the sample https://github.com/evilz/vscode-reveal/tree/master/samples/custom-theme

**Comment by GrumpyLabRat** [comment]
Running the custom.md file included in the samples packaged with the extension produces an internal server error when previewing in VS Code.

**Comment by StefanBrand** [comment]
This works for me:

```
body {
    --r-background-color: red;
}
```

While this only pops up a red background very briefly and then goes back to the black one:

body {
    --background-color: red;
}
