### ISSUE TITLE
4.1.2 Custom themes applying inconsistently 

### ISSUE THREAD

**Issue by CLau72** [evilz/vscode-reveal#852]
After upgrading to version 4.1.2, the custom theme is no longer overriding the default theme on some files within the side-by-side or browser views.

Issue occurrence is inconsistent. I have multiple .md files within the directory that work fine, while others exhibit this behavior. Custom themes working without issue in 4.1.1

**Comment by evilz** [comment]
Thank, I found bug on refreshing when file change and it also make local
resources like images not displayed.

I'm on it

**Comment by CLau72** [comment]
Just updated to 4.13 and it's all looking good to me. Thanks for tackling this so quickly!
