### ISSUE TITLE
Comparison with Merp

### ISSUE THREAD

**Issue by ssbarnea** [evilz/vscode-reveal#893]
First, excuse me for creating a ticket but the discussions are not enabled on this repo and using reviews on marketplace is even worse, as not being really interactive. Thanks for the work on this extension, I really I appreciate it, I maintain a couple of extensions myself, so I known the sweat factor ;)

My bug question is how does this extension related to Merp and do you see their futures? I use hugo with reveal and found use of yours quite easy. Merp seems to have several developers behind and a lot of publicity , like youtube presentations in the last years. On the other hand, I had to dig a little bit to find yours, even if it might seem better.

I am asking this because I know what usually happens with extensions backed by a single person, they even become abandonware or their maintainer collapses under support requests from users.

**Comment by evilz** [comment]
Revealjs is very old. But also has a lot of feature.

I love Merp. Maybe one day I will stop this extension if all nice feature of Revealjs is available in Merp.
