### ISSUE TITLE
Update Menu to allow Theme and Transition changes on the fly

### ISSUE THREAD

**Issue by rleyvasal** [evilz/vscode-reveal#912]
Can the Menu be updated to allow user to change Themes and Transitions on the fly?

Menu plugin from https://github.com/rajgoel/reveal.js-plugins can change the theme of the slides and transition right from the menu.

![menu](https://user-images.githubusercontent.com/61335136/167025792-be740b57-7586-4670-b4d6-030faacd5e12.PNG)

**Comment by evilz** [comment]
I'm not going to do this cause it's not very useful.  Unless a lot of people ask for it.
