### ISSUE TITLE
`font awesome`  not working on `vscode-reveal` 

### ISSUE THREAD

**Issue by rleyvasal** [evilz/vscode-reveal#920]
`font awesome`  not working on `vscode-reveal` presentations?

I have tried the following code:

```markdown

---

## MAKE NOTES ON SLIDES

Did you notice the <i class="fa fa-pencil"></i> button?

```

**Result:**
![fa](https://user-images.githubusercontent.com/61335136/168174727-42763a6d-019a-4106-accc-03c201802ecb.PNG)

**Comment by evilz** [comment]
do it like this https://www.evilznet.com/vscode-reveal/#/markdown/extended-syntax?id=font-awesome-icons
