### ISSUE TITLE
Empty slides on preview

### ISSUE THREAD

**Issue by jazzmagus** [evilz/vscode-reveal#956]
Hi and thanks for this great extension.

Unfortunately I'm experiencing a problem with the preview, by side and on browser.
It seems everything is working properly and the menu shows up correctly but the content is not showing up.

Any idea?

![Schermata 2022-06-12 alle 20 31 08](https://user-images.githubusercontent.com/74508924/173248227-7c0aeb5c-ff20-4738-b0fc-dcb180ef9a70.png)

**Comment by evilz** [comment]
Hello, thank.

It's very strange, without more info I cannot help. I never had this issue.

**Comment by jazzmagus** [comment]
Thanks a lot anyway, in the beginning it was working perfectly.

Just one last question: here are my `setting.json` attributes for `reveal.js`.
Do you notice something weird or missing, comparing to yours?

![settings_json](https://user-images.githubusercontent.com/74508924/173611595-632dda4d-e9dc-41e5-af55-ffb1aac9c87b.png)

**Comment by evilz** [comment]
Ah, maybe it's on the settings. I don't use it. Can you try to remove one by one. If you find something tell me.

**Comment by evilz** [comment]
I think it's `embedded` this setting is not working. please do not use it
